language: python

python:
  - "2.7"

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.6.8

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script: python setup.py test
